apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: campus

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - configmap-extras.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - kafka-init.yaml
  - bridge.yaml
  - influxdb.yaml
  - mosquitto.yaml
  - keycloak.yaml
  - mlflow.yaml
  - ml-consumer.yaml
  - ml-retrain-daemon.yaml
  - api.yaml
  - frontend.yaml
  - postgres-observer.yaml
  - grafana.yaml
  - kong.yaml
  - prometheus.yaml
  - node-exporter.yaml
  - acme-solver-svc.yaml
  - kong-certificate.yaml
  - postgres-vacuum-cron.yaml
  - ml-prediction.yaml
  - simulator.yaml

images:
  - name: ghcr.io/smart-campus-digital-twin/smart-campus-digital-twin-v4/api
    newTag: latest
  - name: ghcr.io/smart-campus-digital-twin/smart-campus-digital-twin-v4/frontend
    newTag: latest
  - name: ghcr.io/smart-campus-digital-twin/smart-campus-digital-twin-v4/ml-consumer
    newTag: latest
  - name: ghcr.io/smart-campus-digital-twin/smart-campus-digital-twin-v4/ml-prediction
    newTag: latest
  - name: ghcr.io/smart-campus-digital-twin/smart-campus-digital-twin-v4/ml-retrain
    newTag: latest
  - name: ghcr.io/smart-campus-digital-twin/smart-campus-digital-twin-v4/simulator
    newTag: latest

configMapGenerator:
  - name: keycloak-realm-config
    files:
      - infra/keycloak/realm-campus.json
  - name: grafana-dashboards-config
    files:
      - infra/grafana/provisioning/dashboards/dashboards.yaml
  - name: grafana-datasources-config
    files:
      - infra/grafana/provisioning/datasources/influxdb.yaml
      - infra/grafana/provisioning/datasources/postgresql.yaml
      - infra/grafana/provisioning/datasources/prometheus.yaml
  - name: grafana-dashboards-json
    files:
      - infra/grafana/dashboards/campus_overview.json
      - infra/grafana/dashboards/node_system_overview.json
  - name: prometheus-config
    files:
      - infra/prometheus/prometheus.yml
  - name: influxdb-init-scripts
    files:
      - init-buckets.sh=infra/influxdb/init-buckets.sh
  - name: kong-template
    files:
      - kong.yml=infra/kong/kong.template.yml
    options:
      disableNameSuffixHash: true
  - name: kong-render-scripts
    files:
      - render_kong_config.py=infra/kong/render_kong_config.py
    options:
      disableNameSuffixHash: true
