apiVersion: v1
data:
  POSTGRES_DB: Y2FtcHVz
  POSTGRES_PASSWORD: Y2FtcHVz
  POSTGRES_USER: Y2FtcHVz
kind: Secret
metadata:
  name: campus-postgres
  namespace: campus
type: Opaque
---
apiVersion: v1
data:
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: Y2hhbmdlbWU=
  DOCKER_INFLUXDB_INIT_BUCKET: Y2FtcHVzX3NlbnNvcnM=
  DOCKER_INFLUXDB_INIT_MODE: c2V0dXA=
  DOCKER_INFLUXDB_INIT_ORG: c21hcnQtY2FtcHVz
  DOCKER_INFLUXDB_INIT_PASSWORD: Y2hhbmdlbWU=
  DOCKER_INFLUXDB_INIT_USERNAME: YWRtaW4=
  INFLUXDB_TOKEN: YmM5ZTY2MTY4M2NkZDI5MTgzMDg0NWY1NDg3NWNmODVmOTBjZjkzN2I1YjE5MWY0YWJhNDIyYmM2MWE4Mzg0Yg==
kind: Secret
metadata:
  name: campus-influxdb
  namespace: campus
type: Opaque
---
apiVersion: v1
data:
  INFLUXDB_BUCKET: Y2FtcHVzX3NlbnNvcnM=
  INFLUXDB_ORG: c21hcnQtY2FtcHVz
  INFLUXDB_TOKEN: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: influxdb-env
  namespace: campus
type: Opaque
---
apiVersion: v1
data:
  KC_DB_PASSWORD: Y2FtcHVz
  KC_DB_USERNAME: Y2FtcHVz
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=
kind: Secret
metadata:
  name: campus-keycloak
  namespace: campus
type: Opaque
---
apiVersion: v1
data:
  KC_DB: cG9zdGdyZXM=
  KC_DB_PASSWORD: Y2FtcHVz
  KC_DB_USERNAME: Y2FtcHVz
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=
kind: Secret
metadata:
  name: keycloak-env
  namespace: campus
type: Opaque
---
apiVersion: v1
data:
  MQTT_PASSWORD: Y2FtcHVz
  MQTT_USERNAME: Y2FtcHVz
kind: Secret
metadata:
  name: campus-mqtt
  namespace: campus
type: Opaque
---
apiVersion: v1
data:
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=
  GF_SECURITY_ADMIN_USER: YWRtaW4=
kind: Secret
metadata:
  name: campus-grafana
  namespace: campus
type: Opaque
---
apiVersion: v1
data:
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=
  GF_SECURITY_ADMIN_USER: YWRtaW4=
kind: Secret
metadata:
  name: grafana-env
  namespace: campus
type: Opaque
---
apiVersion: v1
data:
  CORS_ORIGINS: WyJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCAiaHR0cDovL2xvY2FsaG9zdDozMDAxIiwgImh0dHA6Ly9jYW1wdXMubG9jYWwiXQ==
  JWT_SECRET_KEY: Y2hhbmdlbWUtand0LXNlY3JldC1rZXktZm9yLXByb2R1Y3Rpb24=
kind: Secret
metadata:
  name: api-env
  namespace: campus
type: Opaque
---
apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2NhbXB1czpjYW1wdXNAcG9zdGdyZXM6NTQzMi9jYW1wdXM=
  POSTGRES_DB: Y2FtcHVz
  POSTGRES_PASSWORD: Y2FtcHVz
  POSTGRES_USER: Y2FtcHVz
kind: Secret
metadata:
  name: postgres-env
  namespace: campus
type: Opaque
