"""
Canonical sensor reading — the single schema contract shared by every
pipeline layer (bridge, Flink, Spark, API).

The bridge normalises the simulator's raw dataclass into this model.
All downstream services read and write this shape exactly.

Example wire format (what flows through Kafka topics sensors.*):
{
    "reading_id":  "550e8400-e29b-41d4-a716-446655440000",
    "sensor_id":   "EF101-temp-0",
    "building_id": "EF",
    "floor":       1,
    "room_id":     "EF101",
    "sensor_type": "temperature",
    "value":       24.3,
    "unit":        "celsius",
    "ts":          1745000000000,
    "quality":     1.0
}
"""

from __future__ import annotations

import uuid
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, field_validator, model_validator

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class SensorType(StrEnum):
    TEMPERATURE = "temperature"
    OCCUPANCY   = "occupancy"
    ENERGY      = "energy"


class Unit(StrEnum):
    CELSIUS = "celsius"
    COUNT   = "count"
    WATT    = "watt"


# Maps sensor_type → canonical unit string
CANONICAL_UNIT: dict[SensorType, Unit] = {
    SensorType.TEMPERATURE: Unit.CELSIUS,
    SensorType.OCCUPANCY:   Unit.COUNT,
    SensorType.ENERGY:      Unit.WATT,
}

# Physical plausibility bounds per sensor type.
# Values outside these ranges fail validation at the bridge and are routed
# to the dead-letter topic so bad hardware never pollutes the time-series.
PHYSICAL_BOUNDS: dict[SensorType, tuple[float, float]] = {
    SensorType.TEMPERATURE: (-10.0, 60.0),    # °C — campus is tropical; server rooms can be cooler
    SensorType.OCCUPANCY:   (0.0,  5_000.0),  # headcount
    SensorType.ENERGY:      (0.0,  500_000.0), # W — up to 500 kW for large buildings
}


# ---------------------------------------------------------------------------
# Canonical reading model
# ---------------------------------------------------------------------------

class SensorReading(BaseModel):
    """
    One sensor observation as it flows through every pipeline stage.

    reading_id  — UUID v4 generated by the bridge. Used for exactly-once
                  deduplication in Flink and idempotent InfluxDB writes.
    sensor_id   — Physical device identifier (matches simulator sensor_id).
    building_id — Short building code, e.g. "EF", "IT", "NA".
    floor       — Floor number (0 = ground).
    room_id     — Room code, e.g. "EF101".
    sensor_type — What is being measured (temperature / occupancy / energy).
    value       — Measurement in `unit`.
    unit        — Canonical unit string matching sensor_type.
    ts          — Unix epoch milliseconds, UTC. Short name follows InfluxDB
                  and time-series convention (avoids SQL reserved word clash).
    quality     — Signal quality from 0.0 (degraded) to 1.0 (full). Readings
                  with quality < 0.5 are stored but excluded from aggregations.
    """

    reading_id:  str        = Field(default_factory=lambda: str(uuid.uuid4()))
    sensor_id:   str        = Field(..., description="Physical device ID")
    building_id: str        = Field(..., min_length=1, max_length=64)
    floor:       int        = Field(..., ge=0, le=20)
    room_id:     str        = Field(..., min_length=1, max_length=64)
    sensor_type: SensorType
    value:       float
    unit:        Unit
    ts:          int        = Field(..., gt=0, description="Unix epoch ms, UTC")
    quality:     float      = Field(default=1.0, ge=0.0, le=1.0)

    @field_validator("value")
    @classmethod
    def within_physical_bounds(cls, v: float, info: Any) -> float:
        sensor_type = info.data.get("sensor_type")
        if sensor_type and sensor_type in PHYSICAL_BOUNDS:
            lo, hi = PHYSICAL_BOUNDS[sensor_type]
            if not lo <= v <= hi:
                raise ValueError(
                    f"{sensor_type} value {v!r} is outside physical bounds "
                    f"[{lo}, {hi}] — route to DLQ"
                )
        return v

    @model_validator(mode="after")
    def unit_matches_sensor_type(self) -> SensorReading:
        expected = CANONICAL_UNIT.get(self.sensor_type)
        if expected and self.unit != expected:
            raise ValueError(
                f"unit '{self.unit}' does not match sensor_type "
                f"'{self.sensor_type}' — expected '{expected}'"
            )
        return self

    # ------------------------------------------------------------------
    # Serialisation — every layer uses these, no ad-hoc json.dumps calls
    # ------------------------------------------------------------------

    def to_json(self) -> str:
        return self.model_dump_json()

    @classmethod
    def from_json(cls, raw: str | bytes) -> SensorReading:
        return cls.model_validate_json(raw)

    # ------------------------------------------------------------------
    # Kafka routing helpers
    # ------------------------------------------------------------------

    @property
    def kafka_topic(self) -> str:
        """Destination Kafka topic derived from sensor_type."""
        return f"sensors.{self.sensor_type}"

    @property
    def kafka_key(self) -> bytes:
        """
        Partition key = building_id.
        Keeps all sensors in one building on one partition, giving Flink
        keyed-state jobs locality without per-sensor key explosion.
        """
        return self.building_id.encode()

    # ------------------------------------------------------------------
    # InfluxDB helpers
    # ------------------------------------------------------------------

    @property
    def influx_tags(self) -> dict[str, str]:
        """Low-cardinality dimensions — indexed by InfluxDB for fast filtering."""
        return {
            "building_id": self.building_id,
            "floor":       str(self.floor),
            "room_id":     self.room_id,
            "sensor_type": str(self.sensor_type),
        }

    @property
    def influx_fields(self) -> dict[str, float]:
        """Numeric measurements — stored as fields for aggregation."""
        return {
            "value":   self.value,
            "quality": self.quality,
        }

    def to_line_protocol(self, measurement: str | None = None) -> str:
        """
        InfluxDB line protocol for direct HTTP batch writes.

        Measurement defaults to ``sensor_{sensor_type}`` so each type lives in its
        own InfluxDB measurement and can use the correct field type:
          sensor_occupancy  → value written as Int64  (no decimal people-counts)
          sensor_temperature / sensor_energy → value written as Float64
        """
        if measurement is None:
            measurement = f"sensor_{self.sensor_type}"
        tags   = ",".join(f"{k}={v}" for k, v in self.influx_tags.items())
        fields_parts: list[str] = []
        for k, v in self.influx_fields.items():
            if isinstance(v, str):
                fields_parts.append(f'{k}="{v}"')
            elif k == "value" and self.sensor_type == SensorType.OCCUPANCY:
                fields_parts.append(f"{k}={int(round(v))}i")
            else:
                fields_parts.append(f"{k}={v}")
        fields = ",".join(fields_parts)
        ts_ns  = self.ts * 1_000_000
        return f"{measurement},{tags} {fields} {ts_ns}"

    # ------------------------------------------------------------------
    # Normalisation — bridge converts simulator dataclass → this model
    # ------------------------------------------------------------------

    @classmethod
    def from_simulator(cls, raw: dict[str, Any]) -> SensorReading:
        """
        Convert the simulator's raw dict (shared.models.SensorReading.to_json)
        to the canonical pipeline schema.

        Differences handled here:
          - timestamp_ms → ts
          - unit symbols (°C / W) → canonical strings (celsius / watt)
          - reading_id injected if absent
        """
        unit_map = {"°C": Unit.CELSIUS, "count": Unit.COUNT, "W": Unit.WATT}
        raw_unit = raw.get("unit", "")
        canonical_unit = unit_map.get(raw_unit, raw_unit)

        ts_value = raw.get("ts") or raw.get("timestamp_ms")
        if ts_value is None:
            raise ValueError(
                "Missing required timestamp field: payload must contain 'ts' or 'timestamp_ms'"
            )
        return cls(
            reading_id  = raw.get("reading_id", str(uuid.uuid4())),
            sensor_id   = raw["sensor_id"],
            building_id = raw["building_id"],
            floor       = raw["floor"],
            room_id     = raw["room_id"],
            sensor_type = raw["sensor_type"],
            value       = raw["value"],
            unit        = canonical_unit,
            ts          = ts_value,
            quality     = raw.get("quality", 1.0),
        )
