# Grafana datasource provisioning — InfluxDB 2.x (Flux query language)
# https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources

apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: P951FEA4DE68E13C5
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: $__env{INFLUXDB_ORG}
      defaultBucket: campus_raw
      tlsSkipVerify: true
    secureJsonData:
      token: $__env{INFLUXDB_TOKEN}
    editable: false
